--- 
- :text: Sektioner
  :subitems:
  - :href: "http://sites.google.com/site/arkitektursektionenths/"
    :title: Arkitektursektionen organiserar studenterna vid Arkitekturprogrammet. Vi är en liten sektion med snabbt växande verksamhet!
    :text: Arkitektursektionen (A)
  - :href: "http://www.bergssektionen.se/"
    :title: Bergssektionen organiserar studenter på Civilingenjörsprogrammet i materialdesign.
    :text: Bergssektionen (B)
  - :href: "http://www.d.kth.se/"
    :title: Datasektionen är en av THS bästa sektioner.
    :text: Datasektionen (D)
  - :href: "http://www.doktorandsektionen.se/"
    :title: Doktorandsektionen organiserar doktorander på hela KTH.
    :text: Doktorandsektionen (Dr)
  - :href: "http://www.e.kth.se/"
    :title: Elektrosektionen organiserar teknologer på Civilingenjörsprogrammet i Elektroteknik
    :text: Elektrosektionen (E)
  - :href: "http://www.w-sektionen.se/"
    :title: Energi och Miljö
    :text: Energi och Miljö (W)
  - :href: "http://www.flygsektionen.se/"
    :text: Flygsektionen (T)
  - :href: "http://www.f.kth.se/"
    :title: En av de bästa sektionerna på THS är fysiksektionen
    :text: Fysiksektionen (F)
  - :href: "http://ish.haninge.kth.se/"
    :text: Ingenjörssektionen – Haninge (IsH)
  - :href: "http://www.is-telge.nu/"
    :text: Ingenjörssektionen – Telge (IsT)
  - :href: "http://www.kongligkemi.se/"
    :text: Kemisektionen (K)
  - :href: "http://www.m.kth.se/werkstan/"
    :text: Maskinsektionen (M)
  - :href: "http://www.open-kth.se/"
    :text: Open
  - :href: "http://www.s.kth.se/www/"
    :text: Samhällsbyggnadssektionen (S)
  - :href: "http://www.teknogogen.se/"
    :text: "Sektionen för Civilingenjör & Lärare (CL)"
  - :href: "http://www.iare.nu/"
    :text: Sektionen för industriell ekonomi (I)
  - :href: "http://www.insektionen.se/"
    :text: Sektionen för informations- och nanoteknik (IN)
  - :href: "http://mit-kth.se/"
    :text: Sektionen för Medicinsk informatik och Teknik (MiT)
  - :href: "http://www.medieteknik.org/"
    :text: Sektionen för medieteknik (Media)
- :text: Kårföreningar
  :subitems:
  - :href: "http://www.bergssektionen.se/new/spex.php"
    :title: KBSS är ett spex för alla, oavsett sektionstillhörighet.
    :text: Bergsspexet
  - :href: "http://www.blandaren.se/"
    :title: Blandaren är världens äldsta humortidning, grundad 1863. Tidningen utkommer i december under namnet Gåsblandaren.
    :text: Blandaren
  - :href: "http://designforeningen.se"
    :text: Designföreningen
  - :href: "http://gaytekths.wordpress.com/"
    :title: Gaytek är i första hand till för alla studenter, doktorander och anställda vid KTH som identifierar sig som homo-, bi, trans- eller queerpersoner, men givetvis är alla väkomna oavsett läggning, kön och identitet. 
    :text: Gaytek
  - :href: "http://www.karspexet.se/"
    :title: Kårspexet är en av THS bästa föreningar. Och ett av de allra bästa Spexen." target="_blank
    :text: Kårspexet
  - :href: "https://sites.google.com/site/kthknallpuff/"
    :text: Knallpuff
  - :href: "http://www.knepp.se/"
    :title: Knepp är kårens fotoförening och är öppen för alla THS-medlemmar samt anställda vid KTH,
    :text: Knepp
  - :href: "http://kot.for.ths.kth.se/"
    :title: KOT ägnar sig åt orientering och löpning. KOT deltar i ett antal tävlingar varje år där Norgematchen, en tävling mot Norges Tekniska Högskola i Trondheim, är populär. I föreningen finns allt från nybörjare till elitorienterare. 
    :text: Kongliga Orienteringsteknologerna
  - :href: "http://www.kristnateknologgruppen.se/"
    :title: Kristna teknologgruppen, KTG, har som mål att vara en samlingspunkt på KTH för kristna teknologer och för dig som funderar över livsfrågor eller kristen tro. Vi samlas varje vecka för olika typer av program.
    :text: Kristna Teknologgruppen
  - :href: "http://kthdk.for.ths.kth.se/"
    :title: KTH dykarklubb är en ideell förening för dykare på Teknis och andra. Klubben består av dykare med många typer av certifikat t. ex CMAS, på alla nivåer från nybörjare till instruktör.
    :text: KTH Dykarklubb
  - :href: "http://kthfs.for.ths.kth.se/"
    :title: Verksamheten syftar i allmänhet till att sprida information om finansbranschen och dess finansiella instrument i synnerhet.
    :text: KTH:s Finanssällskap
  - :href: "http://www.kthss.se/"
    :title: KTH:s Segelsällskaps verksamhet avser att tillvarataga medlemmarnas sjösportsintressen samt att verka för ökat intresse för segling bland högskolans elever och vid högskolan och studentkåren anställd personal. 
    :text: KTHSS
  - :href: "http://www.malvinaKTH.se"
    :title: THS kvinnliga nätverk är till för att skapa ett fungerande nätverk bland främst kvinnliga teknologer vid olika sektioner på kth och att upprätthålla kontakter mellan teknologer och näringslivet. 
    :text: Malvina
  - :href: "http://osqstamman.for.ths.kth.se/"
    :title: Osqstämman är en blandad kör med ett 20-tal medlemmar, de flesta KTH-studenter från olika utbildningar. I verksamheten ingår konserter, körinternat, sjungningar hos företag, fester och annat. 
    :text: Osqstämman
  - :href: "http://pq.for.ths.kth.se/"
    :title: PQ är kårens vackra gul-svart-randiga jazzorkester med tillhörande dans.
    :text: PromenadorQuestern
  - :href: "http://www.seek.nu/"
    :title: SEEK är en ideel förening för alla som går på KTH. Ingenjören har med sitt tekniska kunnande och sin problemlösningsförmåga, en nyckelroll i utvecklingen av det hållbara samhället.
    :text: SEEK
  - :href: "http://www.squvalp.se/"
    :title: De år som Quarnevalen ej genomförs arrangerar Quarnevalsstaben Squvalp, vilket är årets största studenthändelse i Stockholm. De utvalda studenterna bygger då fantasifulla och finurliga farkoster som framförs på vatten.
    :text: Squvalp
  - :href: "http://www.stacken.kth.se/"
    :title: Stacken är kårens datorförening. Det här är föreningen för dig som vill kunna göra mer med datorer än vad det finns möjlighet till i skolans terminalsalar, alltifrån egna websidor till hobbysystemadministration och hårdvarumeckande.
    :text: Stacken
  - :href: "http://www.thr.kth.se/"
    :title: Tekniska Högskolans Radioklubb, THR, ägnar sig åt amatörradio, datorer och allmänt elektronikpulande. THR förfogar över en välutrustad radiostation (KV, VHF/UHF, packet-radio), ett bra elektroniklabb och ett bibliotek med ‘elektronisk’ litteratur. 
    :text: Tekniska Högskolans Radioklubb
  - :href: "http://www.ktk.ths.kth.se/"
    :title: Teknologkören har cirka 40 medlemmar och sjunger på allsköns tillställningar.
    :text: Teknologkören
  - :href: "http://www.thsradio.se/"
    :text: THS Radio
  - :href: "http://cvp.foreningar.kth.se/"
    :title: Vi anordnar regelbundet vinprovningar (försök att nämna ett vindistrikt vi inte provsmakat vin ifrån) samt en mycket populär vinkurs där man kan lära sig grunderna i vinprovning såväl som att skilja de vanligaste druvorna åt.
    :text: Vincollegiet
- :href: "http://www.armada.nu/"
  :title: "Armada är THS Arbetsmarknadsdagar"
  :text: Armada
- :href: "http://www.osqledaren.se/"
  :title: "Osqledaren är THS egen tidning"
  :text: Osqledaren
- :href: "http://www.quarnevalen.se/"
  :title: "Quarnevalen hålls vart fjärde år och är Sveriges största studentarrangemang."
  :text: Quarnevalen
- :href: "http://ths.kth.se/international/"
  :title: "THS International"
  :text: THSi

